packages:
  - apps/*
  - libs/*
  - doc/*

catalog:
  '@angular/build': ^20.3.2
  '@angular/cli': ^20.3.4
  '@angular/common': ^20.3.0
  '@angular/compiler': ^20.3.0
  '@angular/compiler-cli': ^20.3.0
  '@angular/core': ^20.3.0
  '@angular/forms': ^20.3.0
  '@angular/platform-browser': ^20.3.0
  '@angular/router': ^20.3.0
  '@braintree/sanitize-url': ~7.1.1
  '@tailwindcss/postcss': ^4.1.14
  '@types/jasmine': ^5.1.0
  cytoscape: ~3.33.1
  cytoscape-cose-bilkent: ~4.1.0
  dayjs: ~1.11.18
  debug: ~4.4.3
  jasmine-core: ^5.9.0
  karma: ^6.4.0
  karma-chrome-launcher: ^3.2.0
  karma-coverage: ^2.2.0
  karma-jasmine: ^5.1.0
  karma-jasmine-html-reporter: ^2.1.0
  mermaid: ~11.12.0
  postcss: ^8.5.0
  rxjs: ^7.8.0
  tailwindcss: ^4.1.14
  tslib: ^2.3.0
  typescript: ^5.9.0
  uuid: ^13.0.0
  vitepress: ~1.6.4
  vitepress-plugin-mermaid: ~2.0.17

onlyBuiltDependencies:
  - esbuild
